-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 01:16:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema basedadosgestai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basedadosgestai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basedadosgestai` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;
USE `basedadosgestai` ;

-- -----------------------------------------------------
-- Table `basedadosgestai`.`areas_estudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`areas_estudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`carga_horaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`carga_horaria` (
  `id_carga` INT NOT NULL AUTO_INCREMENT,
  `tempo_contratual` DECIMAL(4,1) NULL DEFAULT NULL,
  `tempo_aulas` DECIMAL(4,1) NULL DEFAULT NULL,
  `tempo_apoio` DECIMAL(4,1) NULL DEFAULT NULL,
  `tempo_preparacao` DECIMAL(4,1) NULL DEFAULT NULL,
  `percentagem` DECIMAL(4,1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_carga`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`docentes` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_docente` ENUM('carreira', 'contratado') NULL DEFAULT NULL,
  `departamento` ENUM('matemática', 'física', 'gestão') NULL DEFAULT NULL,
  `dados_historico` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`templates` (
  `id_template` INT NOT NULL AUTO_INCREMENT,
  `caminho_ficheiro` VARCHAR(225) NULL DEFAULT NULL,
  `tipo_contrato` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_template`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`contratos` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `numero_renovacao` INT NULL DEFAULT '1',
  `contrato_original_id` INT NULL DEFAULT NULL,
  `data_renovacao` DATE NULL DEFAULT NULL,
  `carga_horaria_id_carga` INT NOT NULL,
  `docentes_id_docente` INT NOT NULL,
  `templates_id_template` INT NOT NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_contratos_carga_horaria1_idx` (`carga_horaria_id_carga` ASC) VISIBLE,
  INDEX `fk_contratos_original_idx` (`contrato_original_id` ASC) VISIBLE,
  INDEX `fk_contratos_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  INDEX `fk_contratos_templates2_idx` (`templates_id_template` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_carga_horaria1`
    FOREIGN KEY (`carga_horaria_id_carga`)
    REFERENCES `basedadosgestai`.`carga_horaria` (`id_carga`),
  CONSTRAINT `fk_contratos_original`
    FOREIGN KEY (`contrato_original_id`)
    REFERENCES `basedadosgestai`.`contratos` (`id_contrato`),
  CONSTRAINT `fk_contratos_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `basedadosgestai`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_templates2`
    FOREIGN KEY (`templates_id_template`)
    REFERENCES `basedadosgestai`.`templates` (`id_template`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`ucs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`ucs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `areas_estudo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ucs_areas_estudo1_idx` (`areas_estudo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ucs_areas_estudo1`
    FOREIGN KEY (`areas_estudo_id`)
    REFERENCES `basedadosgestai`.`areas_estudo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`contrato_ucs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`contrato_ucs` (
  `horas_atribuidas` INT NOT NULL,
  `ucs_id` INT NOT NULL,
  `contratos_id_contrato` INT NOT NULL,
  PRIMARY KEY (`horas_atribuidas`, `ucs_id`, `contratos_id_contrato`),
  INDEX `fk_contrato_ucs_ucs1_idx` (`ucs_id` ASC) VISIBLE,
  INDEX `fk_contrato_ucs_contratos1_idx` (`contratos_id_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_ucs_contratos1`
    FOREIGN KEY (`contratos_id_contrato`)
    REFERENCES `basedadosgestai`.`contratos` (`id_contrato`),
  CONSTRAINT `fk_contrato_ucs_ucs1`
    FOREIGN KEY (`ucs_id`)
    REFERENCES `basedadosgestai`.`ucs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`detalhes_contratados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`detalhes_contratados` (
  `iddetalhes_contratados` INT NOT NULL AUTO_INCREMENT,
  `nif` INT NULL DEFAULT NULL,
  `morada` VARCHAR(255) NULL DEFAULT NULL,
  `docentes_id_docente` INT NOT NULL,
  PRIMARY KEY (`iddetalhes_contratados`),
  INDEX `fk_detalhes_contratados_docentes2_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_detalhes_contratados_docentes2`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `basedadosgestai`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(500) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `data_upload` DATE NOT NULL,
  `versao_contrato` VARCHAR(50) NULL DEFAULT NULL,
  `contratos_id_contrato` INT NOT NULL,
  `docentes_id_docente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documentos_contratos1_idx` (`contratos_id_contrato` ASC) VISIBLE,
  INDEX `fk_documentos_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_contratos1`
    FOREIGN KEY (`contratos_id_contrato`)
    REFERENCES `basedadosgestai`.`contratos` (`id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `basedadosgestai`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`rascunhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`rascunhos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_docente` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_contrato` VARCHAR(100) NULL DEFAULT NULL,
  `dados_formulario` TEXT NOT NULL,
  `data_guardado` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `basedadosgestai`.`cursos_has_ucs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedadosgestai`.`cursos_has_ucs` (
  `cursos_id` INT NOT NULL,
  `ucs_id` INT NOT NULL,
  PRIMARY KEY (`cursos_id`, `ucs_id`),
  INDEX `fk_cursos_has_ucs_ucs1_idx` (`ucs_id` ASC) VISIBLE,
  INDEX `fk_cursos_has_ucs_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_ucs_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `basedadosgestai`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_ucs_ucs1`
    FOREIGN KEY (`ucs_id`)
    REFERENCES `basedadosgestai`.`ucs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
